// Generated by https://quicktype.io

import { EmployeeInterface, ServiceI } from "..";

export interface SpamJobInterface {
  spamJob: SpamJob[];
}

export interface SpamJob {
  _id:       string;
  employee:  EmployeeInterface;
  service:   ServiceI;
  isSpam:    boolean;
  createdAt: string;
  updatedAt: string;
  __v:       number;
}

export interface Employee {
  id:            string;
  name:          string;
  surnames:      string;
  email:         string;
  phone:         string;
  password:      string;
  address:       string;
  district:      string;
  message:       string;
  cv:            null | string;
  birthday:      string;
  dni?:          string;
  findUssocial?: string;
  country:       string;
  typeJob:       string;
  service:       string[];
  servicesId:    string[];
  languages:     any[];
  experiences:   any[];
  skills:        any[];
  status:        boolean;
  currentJob:    boolean;
  createdAt:     string;
  updatedAt:     string;
  __v:           number;
  findSocial?:   string;
  callingCode?:  string;
}

